# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Issues and Research Around People Experiencing Homelessness in King County Working Group
tagline:          ''
description:      'Working group for understanding issues around homelessness at the University of Washington' 
url:              "https://ssdalab.github.io/"
baseurl:          "/kcpehworkinggroup"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/SSDALab/kcpehworkinggroup
